// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfQrRQgq_CWHdc083dOvWNqOd8svpSAXo',
    appId: '1:794543006176:web:0d1ed6944309a8ca7c0b85',
    messagingSenderId: '794543006176',
    projectId: 'photo-gallery-dcd52',
    authDomain: 'photo-gallery-dcd52.firebaseapp.com',
    storageBucket: 'photo-gallery-dcd52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR5b5qxXURBc6IFiiJZmlHPqAlIYJdptU',
    appId: '1:794543006176:android:5331f07960a5fb107c0b85',
    messagingSenderId: '794543006176',
    projectId: 'photo-gallery-dcd52',
    storageBucket: 'photo-gallery-dcd52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj7ImoMMTrEMG8w0lhGOyi5-zjZuXmzdE',
    appId: '1:794543006176:ios:a3437927b010383e7c0b85',
    messagingSenderId: '794543006176',
    projectId: 'photo-gallery-dcd52',
    storageBucket: 'photo-gallery-dcd52.appspot.com',
    iosBundleId: 'com.example.photoGalleryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj7ImoMMTrEMG8w0lhGOyi5-zjZuXmzdE',
    appId: '1:794543006176:ios:a3437927b010383e7c0b85',
    messagingSenderId: '794543006176',
    projectId: 'photo-gallery-dcd52',
    storageBucket: 'photo-gallery-dcd52.appspot.com',
    iosBundleId: 'com.example.photoGalleryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfQrRQgq_CWHdc083dOvWNqOd8svpSAXo',
    appId: '1:794543006176:web:5541baafa530faa37c0b85',
    messagingSenderId: '794543006176',
    projectId: 'photo-gallery-dcd52',
    authDomain: 'photo-gallery-dcd52.firebaseapp.com',
    storageBucket: 'photo-gallery-dcd52.appspot.com',
  );
}
